### ISSUE TITLE
Update the buildspec.yml file with more info 

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/github-bot#5]
In order to use buildspec.yml you need to specify multiple phases usually.  

Something like this would be more useful I think.
```
version: 0.2
phases:
  install:
    commands:
      - # install your test dependencies
      - # install your runtime dependencies
  pre_build:
    commands:
      - # run your tests
artifacts:
  files:
    - ./**/*
# http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
```
